### ISSUE TITLE
Can't get npm Mapnik installed

### ISSUE THREAD

**Issue by azrinsani** [mapsquare/docker-mapnik3#11]
I can succesfully build mapnik however, npm mapnik fails to install.
It gives an error. Is there something missing?

`cd /usr/local/lib`
`npm i mapnik`

Fails. Gives the following error
````
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.0
2 info using node@v19.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/usr/local/lib/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i mapnik
21 verbose argv "i" "mapnik"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-03-15T15_32_00_924Z-
26 verbose logfile /root/.npm/_logs/2023-03-15T15_32_00_924Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 15ms
31 timing config:load:flatten Completed in 0ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 236ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest mapnik@*
39 http fetch GET 200 https://registry.npmjs.org/mapnik 1264ms (cache revalidated)
40 silly placeDep ROOT mapnik@4.5.9 OK for:  want: *
41 silly fetch manifest @mapbox/node-pre-gyp@^1.x
42 silly fetch manifest mapnik-vector-tile@3.0.1
43 silly fetch manifest node-addon-api@~3.1.x
44 http fetch GET 200 https://registry.npmjs.org/node-addon-api 201ms (cache revalidated)
45 http fetch GET 200 https://registry.npmjs.org/@mapbox%2fnode-pre-gyp 220ms (cache revalidated)
46 http fetch GET 200 https://registry.npmjs.org/mapnik-vector-tile 848ms (cache revalidated)
47 timing idealTree:#root Completed in 2128ms
48 silly placeDep ROOT @mapbox/node-pre-gyp@1.0.10 OK for: mapnik@4.5.9 want: ^1.x
49 silly placeDep ROOT mapnik-vector-tile@3.0.1 OK for: mapnik@4.5.9 want: 3.0.1
50 silly placeDep ROOT node-addon-api@3.1.0 OK for: mapnik@4.5.9 want: ~3.1.x
51 silly fetch manifest detect-libc@^2.0.0
52 silly fetch manifest https-proxy-agent@^5.0.0
53 silly fetch manifest make-dir@^3.1.0
54 silly fetch manifest node-fetch@^2.6.7
55 silly fetch manifest nopt@^5.0.0
56 silly fetch manifest npmlog@^5.0.1
57 silly fetch manifest rimraf@^3.0.2
58 silly fetch manifest semver@^7.3.5
59 silly fetch manifest tar@^6.1.11
60 http fetch GET 200 https://registry.npmjs.org/make-dir 95ms (cache revalidated)
61 http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 96ms (cache revalidated)
62 http fetch GET 200 https://registry.npmjs.org/detect-libc 96ms (cache revalidated)
63 http fetch GET 200 https://registry.npmjs.org/npmlog 337ms (cache revalidated)
64 http fetch GET 200 https://registry.npmjs.org/nopt 339ms (cache revalidated)
65 http fetch GET 200 https://registry.npmjs.org/rimraf 339ms (cache revalidated)
66 http fetch GET 200 https://registry.npmjs.org/tar 340ms (cache revalidated)
67 http fetch GET 200 https://registry.npmjs.org/semver 341ms (cache revalidated)
68 http fetch GET 200 https://registry.npmjs.org/node-fetch 343ms (cache revalidated)
69 timing idealTree:node_modules/mapnik Completed in 351ms
70 silly fetch manifest encoding@^0.1.0
71 http fetch GET 200 https://registry.npmjs.org/encoding 93ms (cache revalidated)
72 silly placeDep ROOT detect-libc@2.0.1 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^2.0.0
73 silly placeDep ROOT https-proxy-agent@5.0.1 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^5.0.0
74 silly placeDep ROOT make-dir@3.1.0 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^3.1.0
75 silly placeDep ROOT node-fetch@2.6.9 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^2.6.7
76 silly placeDep ROOT nopt@5.0.0 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^5.0.0
77 silly placeDep ROOT npmlog@5.0.1 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^5.0.1
78 silly placeDep ROOT rimraf@3.0.2 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^3.0.2
79 silly placeDep ROOT semver@7.3.8 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^7.3.5
80 silly placeDep ROOT tar@6.1.13 OK for: @mapbox/node-pre-gyp@1.0.10 want: ^6.1.11
81 silly fetch manifest agent-base@6
82 silly fetch manifest debug@4
83 silly fetch manifest semver@^6.0.0
84 silly fetch manifest whatwg-url@^5.0.0
85 silly fetch manifest abbrev@1
86 silly fetch manifest are-we-there-yet@^2.0.0
87 silly fetch manifest console-control-strings@^1.1.0
88 silly fetch manifest gauge@^3.0.0
89 silly fetch manifest set-blocking@^2.0.0
90 silly fetch manifest glob@^7.1.3
91 silly fetch manifest lru-cache@^6.0.0
92 silly fetch manifest chownr@^2.0.0
93 silly fetch manifest fs-minipass@^2.0.0
94 silly fetch manifest minipass@^4.0.0
95 silly fetch manifest minizlib@^2.1.1
96 silly fetch manifest mkdirp@^1.0.3
97 silly fetch manifest yallist@^4.0.0
98 http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 87ms (cache revalidated)
99 http fetch GET 200 https://registry.npmjs.org/chownr 93ms (cache revalidated)
100 http fetch GET 200 https://registry.npmjs.org/abbrev 97ms (cache revalidated)
101 http fetch GET 200 https://registry.npmjs.org/yallist 91ms (cache revalidated)
102 http fetch GET 200 https://registry.npmjs.org/fs-minipass 94ms (cache revalidated)
103 http fetch GET 200 https://registry.npmjs.org/agent-base 102ms (cache revalidated)
104 http fetch GET 200 https://registry.npmjs.org/gauge 99ms (cache revalidated)
105 http fetch GET 200 https://registry.npmjs.org/lru-cache 99ms (cache revalidated)
106 http fetch GET 200 https://registry.npmjs.org/mkdirp 202ms (cache revalidated)
107 http fetch GET 200 https://registry.npmjs.org/debug 211ms (cache revalidated)
108 http fetch GET 200 https://registry.npmjs.org/set-blocking 210ms (cache revalidated)
109 http fetch GET 200 https://registry.npmjs.org/glob 212ms (cache revalidated)
110 http fetch GET 200 https://registry.npmjs.org/console-control-strings 223ms (cache revalidated)
111 http fetch GET 200 https://registry.npmjs.org/whatwg-url 834ms (cache revalidated)
112 http fetch GET 200 https://registry.npmjs.org/minipass 896ms (cache revalidated)
113 http fetch GET 200 https://registry.npmjs.org/minizlib 1060ms (cache revalidated)
114 timing idealTree:node_modules/@mapbox/node-pre-gyp Completed in 1186ms
115 timing idealTree:node_modules/detect-libc Completed in 0ms
116 silly placeDep ROOT agent-base@6.0.2 OK for: https-proxy-agent@5.0.1 want: 6
117 silly placeDep ROOT debug@4.3.4 OK for: https-proxy-agent@5.0.1 want: 4
118 silly fetch manifest ms@2.1.2
119 http fetch GET 200 https://registry.npmjs.org/ms 86ms (cache revalidated)
120 timing idealTree:node_modules/https-proxy-agent Completed in 94ms
121 timing idealTree:node_modules/agent-base Completed in 0ms
122 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
123 timing idealTree:node_modules/debug Completed in 2ms
124 silly placeDep node_modules/make-dir semver@6.3.0 OK for: make-dir@3.1.0 want: ^6.0.0
125 timing idealTree:node_modules/make-dir Completed in 3ms
126 timing idealTree:node_modules/mapnik-vector-tile Completed in 0ms
127 timing idealTree:node_modules/ms Completed in 0ms
128 timing idealTree:node_modules/node-addon-api Completed in 0ms
129 silly placeDep ROOT whatwg-url@5.0.0 OK for: node-fetch@2.6.9 want: ^5.0.0
130 silly fetch manifest tr46@~0.0.3
131 silly fetch manifest webidl-conversions@^3.0.0
132 http fetch GET 200 https://registry.npmjs.org/tr46 81ms (cache revalidated)
133 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 82ms (cache revalidated)
134 timing idealTree:node_modules/node-fetch Completed in 86ms
135 silly placeDep ROOT abbrev@1.1.1 OK for: nopt@5.0.0 want: 1
136 timing idealTree:node_modules/nopt Completed in 2ms
137 timing idealTree:node_modules/abbrev Completed in 0ms
138 silly placeDep ROOT are-we-there-yet@2.0.0 OK for: npmlog@5.0.1 want: ^2.0.0
139 silly placeDep ROOT console-control-strings@1.1.0 OK for: npmlog@5.0.1 want: ^1.1.0
140 silly placeDep ROOT gauge@3.0.2 OK for: npmlog@5.0.1 want: ^3.0.0
141 silly placeDep ROOT set-blocking@2.0.0 OK for: npmlog@5.0.1 want: ^2.0.0
142 silly fetch manifest delegates@^1.0.0
143 silly fetch manifest readable-stream@^3.6.0
144 silly fetch manifest aproba@^1.0.3 || ^2.0.0
145 silly fetch manifest color-support@^1.1.2
146 silly fetch manifest has-unicode@^2.0.1
147 silly fetch manifest object-assign@^4.1.1
148 silly fetch manifest signal-exit@^3.0.0
149 silly fetch manifest string-width@^4.2.3
150 silly fetch manifest strip-ansi@^6.0.1
151 silly fetch manifest wide-align@^1.1.2
152 http fetch GET 200 https://registry.npmjs.org/delegates 95ms (cache revalidated)
153 http fetch GET 200 https://registry.npmjs.org/object-assign 91ms (cache revalidated)
154 http fetch GET 200 https://registry.npmjs.org/has-unicode 92ms (cache revalidated)
155 http fetch GET 200 https://registry.npmjs.org/aproba 93ms (cache revalidated)
156 http fetch GET 200 https://registry.npmjs.org/string-width 91ms (cache revalidated)
157 http fetch GET 200 https://registry.npmjs.org/readable-stream 96ms (cache revalidated)
158 http fetch GET 200 https://registry.npmjs.org/signal-exit 95ms (cache revalidated)
159 http fetch GET 200 https://registry.npmjs.org/wide-align 94ms (cache revalidated)
160 http fetch GET 200 https://registry.npmjs.org/strip-ansi 96ms (cache revalidated)
161 http fetch GET 200 https://registry.npmjs.org/color-support 826ms (cache revalidated)
162 timing idealTree:node_modules/npmlog Completed in 838ms
163 silly placeDep ROOT delegates@1.0.0 OK for: are-we-there-yet@2.0.0 want: ^1.0.0
164 silly placeDep ROOT readable-stream@3.6.2 OK for: are-we-there-yet@2.0.0 want: ^3.6.0
165 silly fetch manifest inherits@^2.0.3
166 silly fetch manifest string_decoder@^1.1.1
167 silly fetch manifest util-deprecate@^1.0.1
168 http fetch GET 200 https://registry.npmjs.org/string_decoder 101ms (cache revalidated)
169 http fetch GET 200 https://registry.npmjs.org/util-deprecate 101ms (cache revalidated)
170 http fetch GET 200 https://registry.npmjs.org/inherits 279ms (cache revalidated)
171 timing idealTree:node_modules/are-we-there-yet Completed in 292ms
172 timing idealTree:node_modules/console-control-strings Completed in 0ms
173 timing idealTree:node_modules/delegates Completed in 0ms
174 silly placeDep ROOT aproba@2.0.0 OK for: gauge@3.0.2 want: ^1.0.3 || ^2.0.0
175 silly placeDep ROOT color-support@1.1.3 OK for: gauge@3.0.2 want: ^1.1.2
176 silly placeDep ROOT has-unicode@2.0.1 OK for: gauge@3.0.2 want: ^2.0.1
177 silly placeDep ROOT object-assign@4.1.1 OK for: gauge@3.0.2 want: ^4.1.1
178 silly placeDep ROOT signal-exit@3.0.7 OK for: gauge@3.0.2 want: ^3.0.0
179 silly placeDep ROOT string-width@4.2.3 OK for: gauge@3.0.2 want: ^4.2.3
180 silly placeDep ROOT strip-ansi@6.0.1 OK for: gauge@3.0.2 want: ^6.0.1
181 silly placeDep ROOT wide-align@1.1.5 OK for: gauge@3.0.2 want: ^1.1.2
182 silly fetch manifest emoji-regex@^8.0.0
183 silly fetch manifest is-fullwidth-code-point@^3.0.0
184 silly fetch manifest ansi-regex@^5.0.1
185 http fetch GET 200 https://registry.npmjs.org/emoji-regex 90ms (cache revalidated)
186 http fetch GET 200 https://registry.npmjs.org/ansi-regex 90ms (cache revalidated)
187 http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 91ms (cache revalidated)
188 timing idealTree:node_modules/gauge Completed in 112ms
189 timing idealTree:node_modules/aproba Completed in 0ms
190 timing idealTree:node_modules/color-support Completed in 0ms
191 timing idealTree:node_modules/has-unicode Completed in 0ms
192 timing idealTree:node_modules/object-assign Completed in 0ms
193 silly placeDep ROOT inherits@2.0.4 OK for: readable-stream@3.6.2 want: ^2.0.3
194 silly placeDep ROOT string_decoder@1.3.0 OK for: readable-stream@3.6.2 want: ^1.1.1
195 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@3.6.2 want: ^1.0.1
196 silly fetch manifest safe-buffer@~5.2.0
197 http fetch GET 200 https://registry.npmjs.org/safe-buffer 84ms (cache revalidated)
198 timing idealTree:node_modules/readable-stream Completed in 90ms
199 timing idealTree:node_modules/inherits Completed in 0ms
200 silly placeDep ROOT glob@7.2.3 OK for: rimraf@3.0.2 want: ^7.1.3
201 silly fetch manifest fs.realpath@^1.0.0
202 silly fetch manifest inflight@^1.0.4
203 silly fetch manifest minimatch@^3.1.1
204 silly fetch manifest once@^1.3.0
205 silly fetch manifest path-is-absolute@^1.0.0
206 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 90ms (cache revalidated)
207 http fetch GET 200 https://registry.npmjs.org/inflight 93ms (cache revalidated)
208 http fetch GET 200 https://registry.npmjs.org/once 92ms (cache revalidated)
209 http fetch GET 200 https://registry.npmjs.org/minimatch 93ms (cache revalidated)
210 http fetch GET 200 https://registry.npmjs.org/fs.realpath 99ms (cache revalidated)
211 timing idealTree:node_modules/rimraf Completed in 102ms
212 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.2.3 want: ^1.0.0
213 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.2.3 want: ^1.0.4
214 silly placeDep ROOT minimatch@3.1.2 OK for: glob@7.2.3 want: ^3.1.1
215 silly placeDep ROOT once@1.4.0 OK for: glob@7.2.3 want: ^1.3.0
216 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.2.3 want: ^1.0.0
217 silly fetch manifest wrappy@1
218 silly fetch manifest brace-expansion@^1.1.7
219 http fetch GET 200 https://registry.npmjs.org/wrappy 77ms (cache revalidated)
220 http fetch GET 200 https://registry.npmjs.org/brace-expansion 79ms (cache revalidated)
221 timing idealTree:node_modules/glob Completed in 87ms
222 timing idealTree:node_modules/fs.realpath Completed in 0ms
223 silly placeDep ROOT wrappy@1.0.2 OK for: inflight@1.0.6 want: 1
224 timing idealTree:node_modules/inflight Completed in 2ms
225 silly placeDep ROOT brace-expansion@1.1.11 OK for: minimatch@3.1.2 want: ^1.1.7
226 silly fetch manifest balanced-match@^1.0.0
227 silly fetch manifest concat-map@0.0.1
228 http fetch GET 200 https://registry.npmjs.org/balanced-match 82ms (cache revalidated)
229 http fetch GET 200 https://registry.npmjs.org/concat-map 83ms (cache revalidated)
230 timing idealTree:node_modules/minimatch Completed in 86ms
231 silly placeDep ROOT balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
232 silly placeDep ROOT concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
233 timing idealTree:node_modules/brace-expansion Completed in 5ms
234 timing idealTree:node_modules/balanced-match Completed in 0ms
235 timing idealTree:node_modules/concat-map Completed in 0ms
236 timing idealTree:node_modules/once Completed in 0ms
237 timing idealTree:node_modules/path-is-absolute Completed in 0ms
238 silly placeDep ROOT lru-cache@6.0.0 OK for: semver@7.3.8 want: ^6.0.0
239 timing idealTree:node_modules/semver Completed in 2ms
240 silly placeDep ROOT yallist@4.0.0 OK for: lru-cache@6.0.0 want: ^4.0.0
241 timing idealTree:node_modules/lru-cache Completed in 2ms
242 timing idealTree:node_modules/set-blocking Completed in 0ms
243 timing idealTree:node_modules/signal-exit Completed in 0ms
244 silly placeDep ROOT safe-buffer@5.2.1 OK for: string_decoder@1.3.0 want: ~5.2.0
245 timing idealTree:node_modules/string_decoder Completed in 1ms
246 timing idealTree:node_modules/safe-buffer Completed in 0ms
247 silly placeDep ROOT emoji-regex@8.0.0 OK for: string-width@4.2.3 want: ^8.0.0
248 silly placeDep ROOT is-fullwidth-code-point@3.0.0 OK for: string-width@4.2.3 want: ^3.0.0
249 timing idealTree:node_modules/string-width Completed in 2ms
250 timing idealTree:node_modules/emoji-regex Completed in 0ms
251 timing idealTree:node_modules/is-fullwidth-code-point Completed in 0ms
252 silly placeDep ROOT ansi-regex@5.0.1 OK for: strip-ansi@6.0.1 want: ^5.0.1
253 timing idealTree:node_modules/strip-ansi Completed in 1ms
254 timing idealTree:node_modules/ansi-regex Completed in 0ms
255 silly placeDep ROOT chownr@2.0.0 OK for: tar@6.1.13 want: ^2.0.0
256 silly placeDep ROOT fs-minipass@2.1.0 OK for: tar@6.1.13 want: ^2.0.0
257 silly placeDep ROOT minipass@4.2.5 OK for: tar@6.1.13 want: ^4.0.0
258 silly placeDep ROOT minizlib@2.1.2 OK for: tar@6.1.13 want: ^2.1.1
259 silly placeDep ROOT mkdirp@1.0.4 OK for: tar@6.1.13 want: ^1.0.3
260 silly fetch manifest minipass@^3.0.0
261 timing idealTree:node_modules/tar Completed in 7ms
262 timing idealTree:node_modules/chownr Completed in 0ms
263 silly placeDep node_modules/fs-minipass minipass@3.3.6 OK for: fs-minipass@2.1.0 want: ^3.0.0
264 timing idealTree:node_modules/fs-minipass Completed in 1ms
265 timing idealTree:node_modules/minipass Completed in 0ms
266 silly placeDep node_modules/minizlib minipass@3.3.6 OK for: minizlib@2.1.2 want: ^3.0.0
267 timing idealTree:node_modules/minizlib Completed in 1ms
268 timing idealTree:node_modules/mkdirp Completed in 0ms
269 timing idealTree:node_modules/util-deprecate Completed in 0ms
270 silly placeDep ROOT tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
271 silly placeDep ROOT webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
272 timing idealTree:node_modules/whatwg-url Completed in 2ms
273 timing idealTree:node_modules/tr46 Completed in 0ms
274 timing idealTree:node_modules/webidl-conversions Completed in 0ms
275 timing idealTree:node_modules/wide-align Completed in 0ms
276 timing idealTree:node_modules/wrappy Completed in 0ms
277 timing idealTree:node_modules/yallist Completed in 0ms
278 timing idealTree:node_modules/fs-minipass/node_modules/minipass Completed in 0ms
279 timing idealTree:node_modules/make-dir/node_modules/semver Completed in 0ms
280 timing idealTree:node_modules/minizlib/node_modules/minipass Completed in 0ms
281 timing idealTree:buildDeps Completed in 5493ms
282 timing idealTree:fixDepFlags Completed in 38ms
283 timing idealTree Completed in 5770ms
284 timing reify:loadTrees Completed in 5770ms
285 timing reify:diffTrees Completed in 2ms
286 silly reify mark retired [
286 silly reify   '/usr/local/lib/node_modules/corepack',
286 silly reify   '/usr/local/lib/node_modules/.bin/corepack',
286 silly reify   '/usr/local/lib/node_modules/.bin/pnpm',
286 silly reify   '/usr/local/lib/node_modules/.bin/pnpx',
286 silly reify   '/usr/local/lib/node_modules/.bin/yarn',
286 silly reify   '/usr/local/lib/node_modules/.bin/yarnpkg'
286 silly reify ]
287 silly reify mark retired [
287 silly reify   '/usr/local/lib/node_modules/npm',
287 silly reify   '/usr/local/lib/node_modules/.bin/npm',
287 silly reify   '/usr/local/lib/node_modules/.bin/npx'
287 silly reify ]
288 silly reify moves {
288 silly reify   '/usr/local/lib/node_modules/corepack': '/usr/local/lib/node_modules/.corepack-xqcTrkeV',
288 silly reify   '/usr/local/lib/node_modules/.bin/corepack': '/usr/local/lib/node_modules/.bin/.corepack-VxWCwg43',
288 silly reify   '/usr/local/lib/node_modules/.bin/pnpm': '/usr/local/lib/node_modules/.bin/.pnpm-MXQYNYc9',
288 silly reify   '/usr/local/lib/node_modules/.bin/pnpx': '/usr/local/lib/node_modules/.bin/.pnpx-GAr7YVz3',
288 silly reify   '/usr/local/lib/node_modules/.bin/yarn': '/usr/local/lib/node_modules/.bin/.yarn-TdydQJ2W',
288 silly reify   '/usr/local/lib/node_modules/.bin/yarnpkg': '/usr/local/lib/node_modules/.bin/.yarnpkg-YKxbPiFc',
288 silly reify   '/usr/local/lib/node_modules/npm': '/usr/local/lib/node_modules/.npm-i9nnxROI',
288 silly reify   '/usr/local/lib/node_modules/.bin/npm': '/usr/local/lib/node_modules/.bin/.npm-KnKvtYRz',
288 silly reify   '/usr/local/lib/node_modules/.bin/npx': '/usr/local/lib/node_modules/.bin/.npx-7XrdYQyd'
288 silly reify }
289 timing reify:retireShallow Completed in 4ms
290 timing reify:createSparse Completed in 3ms
291 timing reify:loadBundles Completed in 0ms
292 timing reifyNode:node_modules/chownr Completed in 106ms
293 timing reifyNode:node_modules/brace-expansion Completed in 106ms
294 timing reifyNode:node_modules/wide-align Completed in 106ms
295 timing reifyNode:node_modules/abbrev Completed in 106ms
296 timing reifyNode:node_modules/ms Completed in 106ms
297 timing reifyNode:node_modules/fs-minipass Completed in 109ms
298 timing reifyNode:node_modules/is-fullwidth-code-point Completed in 109ms
299 timing reifyNode:node_modules/ansi-regex Completed in 109ms
300 timing reifyNode:node_modules/lru-cache Completed in 109ms
301 timing reifyNode:node_modules/wrappy Completed in 109ms
302 timing reifyNode:node_modules/path-is-absolute Completed in 109ms
303 timing reifyNode:node_modules/once Completed in 110ms
304 timing reifyNode:node_modules/inflight Completed in 110ms
305 timing reifyNode:node_modules/inherits Completed in 109ms
306 timing reifyNode:node_modules/strip-ansi Completed in 109ms
307 timing reifyNode:node_modules/string-width Completed in 109ms
308 timing reifyNode:node_modules/object-assign Completed in 109ms
309 timing reifyNode:node_modules/has-unicode Completed in 109ms
310 timing reifyNode:node_modules/signal-exit Completed in 109ms
311 timing reifyNode:node_modules/aproba Completed in 109ms
312 timing reifyNode:node_modules/make-dir Completed in 110ms
313 timing reifyNode:node_modules/npmlog Completed in 110ms
314 timing reifyNode:node_modules/webidl-conversions Completed in 113ms
315 timing reifyNode:node_modules/yallist Completed in 112ms
316 timing reifyNode:node_modules/balanced-match Completed in 113ms
317 timing reifyNode:node_modules/string_decoder Completed in 112ms
318 timing reifyNode:node_modules/console-control-strings Completed in 112ms
319 timing reifyNode:node_modules/set-blocking Completed in 112ms
320 timing reifyNode:node_modules/minizlib Completed in 115ms
321 timing reifyNode:node_modules/minimatch Completed in 115ms
322 timing reifyNode:node_modules/util-deprecate Completed in 114ms
323 timing reifyNode:node_modules/fs.realpath Completed in 115ms
324 timing reifyNode:node_modules/color-support Completed in 115ms
325 timing reifyNode:node_modules/safe-buffer Completed in 117ms
326 timing reifyNode:node_modules/rimraf Completed in 117ms
327 timing reifyNode:node_modules/debug Completed in 118ms
328 timing reifyNode:node_modules/detect-libc Completed in 119ms
329 timing reifyNode:node_modules/concat-map Completed in 121ms
330 timing reifyNode:node_modules/delegates Completed in 120ms
331 timing reifyNode:node_modules/are-we-there-yet Completed in 120ms
332 timing reifyNode:node_modules/nopt Completed in 120ms
333 timing reifyNode:node_modules/fs-minipass/node_modules/minipass Completed in 122ms
334 timing reifyNode:node_modules/minizlib/node_modules/minipass Completed in 122ms
335 timing reifyNode:node_modules/glob Completed in 122ms
336 timing reifyNode:node_modules/minipass Completed in 123ms
337 timing reifyNode:node_modules/emoji-regex Completed in 123ms
338 timing reifyNode:node_modules/whatwg-url Completed in 123ms
339 timing reifyNode:node_modules/make-dir/node_modules/semver Completed in 124ms
340 timing reifyNode:node_modules/mkdirp Completed in 125ms
341 timing reifyNode:node_modules/https-proxy-agent Completed in 126ms
342 timing reifyNode:node_modules/agent-base Completed in 126ms
343 timing reifyNode:node_modules/node-fetch Completed in 127ms
344 timing reifyNode:node_modules/gauge Completed in 129ms
345 timing reifyNode:node_modules/tr46 Completed in 131ms
346 timing reifyNode:node_modules/readable-stream Completed in 137ms
347 timing reifyNode:node_modules/tar Completed in 139ms
348 timing reifyNode:node_modules/@mapbox/node-pre-gyp Completed in 141ms
349 timing reifyNode:node_modules/semver Completed in 143ms
350 timing reifyNode:node_modules/mapnik-vector-tile Completed in 146ms
351 timing reifyNode:node_modules/node-addon-api Completed in 162ms
352 timing reifyNode:node_modules/mapnik Completed in 186ms
353 timing reify:unpack Completed in 189ms
354 timing reify:unretire Completed in 0ms
355 timing build:queue Completed in 2ms
356 timing build:link:node_modules/@mapbox/node-pre-gyp Completed in 2ms
357 timing build:link:node_modules/color-support Completed in 2ms
358 timing build:link:node_modules/mapnik Completed in 1ms
359 timing build:link:node_modules/nopt Completed in 1ms
360 timing build:link:node_modules/mkdirp Completed in 1ms
361 timing build:link:node_modules/semver Completed in 1ms
362 timing build:link:node_modules/rimraf Completed in 1ms
363 timing build:link:node_modules/make-dir/node_modules/semver Completed in 1ms
364 timing build:link Completed in 2ms
365 info run mapnik@4.5.9 install node_modules/mapnik node-pre-gyp install --fallback-to-build
366 info run mapnik@4.5.9 install { code: 1, signal: null }
367 timing reify:rollback:createSparse Completed in 40ms
368 timing reify:rollback:retireShallow Completed in 2ms
369 timing command:i Completed in 7378ms
370 verbose stack Error: command failed
370 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
370 verbose stack     at ChildProcess.emit (node:events:512:28)
370 verbose stack     at maybeClose (node:internal/child_process:1098:16)
370 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
371 verbose pkgid mapnik@4.5.9
372 verbose cwd /usr/local/lib
373 verbose Linux 5.15.49-linuxkit
374 verbose node v19.7.0
375 verbose npm  v9.5.0
376 error code 1
377 error path /usr/local/lib/node_modules/mapnik
378 error command failed
379 error command sh -c node-pre-gyp install --fallback-to-build
380 error Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
381 error node-pre-gyp info it worked if it ends with ok
381 error node-pre-gyp info using node-pre-gyp@1.0.10
381 error node-pre-gyp info using node@19.7.0 | linux | arm64
381 error node-pre-gyp info check checked for "/usr/local/lib/node_modules/mapnik/lib/binding/mapnik.node" (not found)
381 error node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/linux-arm64.tar.gz
381 error node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/linux-arm64.tar.gz 
381 error node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.5.9 and node@19.7.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
381 error node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/linux-arm64.tar.gz 
381 error node-pre-gyp ERR! build error 
381 error node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
381 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:83:23)
381 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
381 error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
381 error node-pre-gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
381 error node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
381 error node-pre-gyp ERR! System Linux 5.15.49-linuxkit
381 error node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
381 error node-pre-gyp ERR! cwd /usr/local/lib/node_modules/mapnik
381 error node-pre-gyp ERR! node -v v19.7.0
381 error node-pre-gyp ERR! node-pre-gyp -v v1.0.10
381 error node-pre-gyp ERR! not ok
382 verbose exit 1
383 timing npm Completed in 7404ms
384 verbose unfinished npm timer reify 1678894320949
385 verbose unfinished npm timer reify:build 1678894326919
386 verbose unfinished npm timer build 1678894326920
387 verbose unfinished npm timer build:deps 1678894326920
388 verbose unfinished npm timer build:run:install 1678894326924
389 verbose unfinished npm timer build:run:install:node_modules/mapnik 1678894326925
390 verbose code 1
391 error A complete log of this run can be found in:
391 error     /root/.npm/_logs/2023-03-15T15_32_00_924Z-debug-0.log
````

**Comment by Joxit** [comment]
Hi, thank you for posting an issue. I think you should contact the owner of the library you are trying to install : https://github.com/mapnik/node-mapnik and tell them you want to use a manually installed version of mapnik

As I can see in your error
```
381 error node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.5.9 and node@19.7.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
381 error node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/linux-arm64.tar.gz 
```

`Pre-built binaries not installable for mapnik@4.5.9 and node@19.7.0` You have a wrong version of node and this library uses a pre-built binary, not an installed one, so not compatible with this docker image.
